create database customer_behavior;
select * from customer;
-- What is the total revenue generated by male vs female customers?
select gender , sum(purchase_amount)as Revenue
from customer
group by gender;

-- which customers used a discount but still spent more than the average purchase amount 
select customer_id, purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >=(select avg(purchase_amount) from customer);

-- which are the top five products with the highest average review rating 
select item_purchased,round(AVG(review_rating),2)AS AVERAGE_PRODUCT_RATING from customer 
group by item_purchased 
order by avg(review_rating) desc 
limit 5; 

-- comapare the average purchase amounts between standard and express shipping.
select shipping_type,avg(purchase_amount)
from customer 
where shipping_type in ('standard','express')
group by shipping_type;

-- do subscribe customer spend more compare average spend and total revenue 
-- between subscribers and non subscribers
select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- which five products have the highest percentage of purchase with discounts applied.
select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end) / count(*) *100,2) as discount_rate 
from customer 
Group by item_purchased
order by discount_rate desc 
limit 5;

-- what are the top three most purchased products within each category
SELECT category, item_purchased, total_purchases
FROM (
  SELECT 
    category,
    item_purchased,
    COUNT(*) AS total_purchases,
    ROW_NUMBER() OVER (
      PARTITION BY category
      ORDER BY COUNT(*) DESC
    ) AS rank_num
  FROM customer
  GROUP BY category, item_purchased
) ranked
WHERE rank_num <= 3
ORDER BY category, total_purchases DESC;


-- Are customer wo are repeat buyers (more than five frevious purchases) also likely to subscibe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- What is the revenue contribution of each age group 
select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;



